volumes:
  caddy_data:
  caddy_config:
  postgresql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/data/postgresql
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/data/redis

services:
  # Spring Boot Backend
  backend:
    build:
      context: BE
      dockerfile: Dockerfile
    container_name: certis-backend
    networks:
      - cert-is
    env_file:
      - ./BE/.env.prod  # 기본적으로 운영환경 설정 사용
    environment:
      # PostgreSQL 연결 설정
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT}
      # 프로파일 및 기타 설정
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EMBEDDED_POSTGRES_ENABLED=${EMBEDDED_POSTGRES_ENABLED}
      - EMBEDDED_REDIS_ENABLED=${EMBEDDED_REDIS_ENABLED}
      - CACHE_TYPE=${CACHE_TYPE}
      # CORS 설정
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      # JVM 최적화
      - JAVA_OPTS=${JAVA_OPTS}
    init: true
    expose:
      - 8080
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # PostgreSQL Database (업데이트된 버전: 15.14)
  postgresql:
    image: postgres:15.14-alpine
    container_name: certis-postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./db/migration:/docker-entrypoint-initdb.d
    networks:
      - cert-is
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=${POSTGRES_MAX_CONNECTIONS}
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS}
      -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE}
      -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM}
      -c checkpoint_completion_target=0.9
      -c wal_buffers=${POSTGRES_WAL_BUFFERS}
      -c default_statistics_target=100

  # Redis Service (업데이트된 버전: latest)
  redis:
    image: redis:latest
    container_name: certis-redis
    volumes:
      - redis-data:/data
    networks:
      - cert-is
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Caddy Reverse Proxy (API Gateway)
  caddy:
    image: caddy:${CADDY_VERSION}
    container_name: certis-caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "${CADDY_HTTP_PORT}:80"
      - "${CADDY_HTTPS_PORT}:443"
    networks:
      - cert-is
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cert-is:
    driver: bridge